---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "angular"
  namespace: "angular"
  labels:
    app: "angular"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "angular"
  template:
    metadata:
      labels:
        app: "angular"
    spec:
      containers:
      - name: "angular"
        image: "gcr.io/mobbuy-qa-microservices/angular:0.0.7"


---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
        external-dns.alpha.kubernetes.io/hostname: "angular.qa.appmobbuy.tech"
  labels:
    app: "angular"
  name: "angular"
  namespace: "angular"
spec:
  externalTrafficPolicy: "Local"
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 80
  selector:
   app: "angular"
  type: "LoadBalancer"
