export enum TransactionBatchStatusEnum {
  CREATED = 'CREATED',
  IN_PROCESS = 'IN_PROCESS',
  PROCESSED_BY_RECURRENCE_WITH_SUCCESS = 'PROCESSED_BY_RECURRENCE_WITH_SUCCESS',
  FIRST_PROCESS_WITH_FAIL = 'FIRST_PROCESS_WITH_FAIL',
  FIRST_PROCESS_WITH_SUCCESS = 'FIRST_PROCESS_WITH_SUCCESS',
  SECOND_PROCESS_WITH_FAIL = 'SECOND_PROCESS_WITH_FAIL',
  SECOND_PROCESS_WITH_SUCCESS = 'SECOND_PROCESS_WITH_SUCCESS'
}